function domFunc (){
	document.querySelectorAll("input , textarea").forEach(
	(elm)=>{	
		elm.addEventListener(
			"input",
			function(){
				obj=document.querySelector("#input");			
				br=obj.value;
				br=br.replace(/3/g,"ع");
				br=br.replace(/a/g,"ا");
				br=br.replace(/b/g,"ب");
				br=br.replace(/p/g,"ب");
				br=br.replace(/t/g,"ت");
				br=br.replace(/7/g,"ح");
				br=br.replace(/c/g,"ث");
				br=br.replace(/ت'/g,"ث");
				br=br.replace(/j/g,"ج");
				br=br.replace(/ح'/g,"خ");
				br=br.replace(/x/g,"خ");
				br=br.replace(/5/g,"خ");
				br=br.replace(/k/g,"ك");
				br=br.replace(/d/g,"د");
				br=br.replace(/د'/g,"ذ");
				br=br.replace(/r/g,"ر");
				br=br.replace(/z/g,"ز");
				br=br.replace(/ر'/g,"ز");
				br=br.replace(/R/g,"ز");
				br=br.replace(/s/g,"س");
				br=br.replace(/ثه/g,"ش");
				br=br.replace(/C/g,"ش");
				br=br.replace(/س'/g,"ش");
				br=br.replace(/S/g,"ص");
				br=br.replace(/ص'/g,"ض");
				br=br.replace(/D/g,"ض");
				br=br.replace(/T/g,"ط");
				br=br.replace(/6/g,"ط");
				br=br.replace(/ط'/g,"ظ");
				br=br.replace(/Z/g,"ظ");
				br=br.replace(/ع'/g,"غ");
				br=br.replace(/gه/g,"غ");
				br=br.replace(/f/g,"ف");
				br=br.replace(/ك'/g,"ق");
				br=br.replace(/K/g,"ق");
				br=br.replace(/9/g,"ق");
				br=br.replace(/q/g,"ق");
				br=br.replace(/l/g,"ل");
				br=br.replace(/m/g,"م");
				br=br.replace(/n/g,"ن");
				br=br.replace(/h/g,"ه");
				br=br.replace(/w/g,"و");
				br=br.replace(/o/g,"و");
				br=br.replace(/u/g,"و");
				br=br.replace(/y/g,"ي");
				br=br.replace(/i/g,"ي");
				br=br.replace(/و'/g,"ؤ");
				br=br.replace(/وء/g,"ؤ");
				br=br.replace(/ءي/g,"ئ");
				br=br.replace(/ء#/g,"ئ");
				br=br.replace(/ي'/g,"ئ");
				br=br.replace(/#/g,"ى");
				br=br.replace(/آآ/g,"ى");
				br=br.replace(/اءء/g,"إ");
				br=br.replace(/I/g,"إ");
				br=br.replace(/A/g,"إ");
				br=br.replace(/ءا/g,"أ");
				br=br.replace(/ا'/g,"أ");
				br=br.replace(/_/g,"ـ");
				br=br.replace(/2/g,"ء");
				br=br.replace(/-/g,"ء");
				br=br.replace(/ه'/g,"ة");
				br=br.replace(/H/g,"ة");
				
				//7arakat
				br=br.replace(/ا=/g,"َ");
				br=br.replace(/و=/g,"ُ");
				br=br.replace(/ي=/g,"ِ");
				br=br.replace(/ون=/g,"ٌ");
				br=br.replace(/ين=/g,"ٍ");
				br=br.replace(/ان=/g,"ً");
				br=br.replace(/1/g,"أ");
				obj.value = br
			}
		)
		}
		)}
document.addEventListener('DOMContentLoaded', domFunc);